steps:
- name: node:10.15.1
  entrypoint: npm
  args: ["install"]
- name: node:10.15.1
  entrypoint: npm
  args: ["install","--prefix","./react_front_end"]
- name: node:10.15.1
  entrypoint: npm
  args: ["run", "build","--prefix","./react_front_end"]
- name: node:10.15.1
  entrypoint: npm
  args: ["run", "create-env"]
  env:
    - 'MONGO_USER=${_MONGO_USER}'
    - 'MONGO_PASSWORD=${_MONGO_PASSWORD}'
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"